export {default as Navbar} from './Navbar'
export {default as Hero} from './Hero'
export {default as Popular} from './Popular'
export {default as Menu} from './Menu'
export {default as Testimonial} from './Testimonial'
export {default as Services} from './Services'
export {default as Footer} from './Footer'